#!/bin/sh
# shellcheck disable=SC2016
set -e -u

SPHINX_DOCS="architecture"

exec >generated-config-doc.yml
cat "${0%/*}/base.yml"
cat "${0%/*}/base-doc.yml"

for make in doc/*/Makefile
do
	[ -f "$make" ] || continue
	path="${make%/Makefile}"
	pkg="${path##*/}"
    extends_line='  extends: .doc'

    if echo $SPHINX_DOCS | grep -w "$pkg" > /dev/null; then
        extends_line='  extends: .sphinx-doc'
    fi
	echo
	echo "build ${pkg}:"
	echo '  variables:'
	echo "    base: $path"
	echo "$extends_line"
	echo '  rules:'
	echo '    - if: "$CI_COMMIT_MESSAGE =~ /skip-doc/ || $pipeline =~ /skip-doc/"'
	echo '      when: never'
	echo '    - if: "$CI_COMMIT_MESSAGE =~ /force-doc/ || $pipeline =~ /force-doc/"'
	echo '    - changes:'
	echo "      - ${path}/**/*"
done
