#!/bin/sh
# shellcheck disable=SC2016
set -e -u

SPHINX_DOCS="architecture"

exec >generated-config-doc.yml
cat "${0%/*}/base.yml"
cat "${0%/*}/base-doc.yml"

for make in doc/*/Makefile
do
	[ -f "$make" ] || continue
	path="${make%/Makefile}"
	pkg="${path##*/}"

    if echo $SPHINX_DOCS | grep -w "$pkg" > /dev/null; then
		echo
		echo "build ${pkg} html:"
		echo '  variables:'
		echo "    base: $path"
		echo '  extends: .sphinx-html'
		echo '  rules:'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /skip-doc/ || $pipeline =~ /skip-doc/"'
		echo '      when: never'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /force-doc/ || $pipeline =~ /force-doc/"'
		echo '    - changes:'
		echo "      - ${path}/**/*"

		echo
		echo "build ${pkg} pdf:"
		echo '  variables:'
		echo "    base: $path"
		echo '  extends: .sphinx-pdf'
		echo '  rules:'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /skip-doc/ || $pipeline =~ /skip-doc/"'
		echo '      when: never'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /force-doc/ || $pipeline =~ /force-doc/"'
		echo '    - changes:'
		echo "      - ${path}/**/*"

		echo
		echo "build ${pkg} linkcheck:"
		echo '  variables:'
		echo "    base: $path"
		echo '  extends: .sphinx-linkcheck'
		echo '  rules:'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /skip-doc/ || $pipeline =~ /skip-doc/"'
		echo '      when: never'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /force-doc/ || $pipeline =~ /force-doc/"'
		echo '    - changes:'
		echo "      - ${path}/**/*"

		echo
		echo "build ${pkg} spelling:"
		echo '  variables:'
		echo "    base: $path"
		echo '  extends: .sphinx-spelling'
		echo '  rules:'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /skip-doc/ || $pipeline =~ /skip-doc/"'
		echo '      when: never'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /force-doc/ || $pipeline =~ /force-doc/"'
		echo '    - changes:'
		echo "      - ${path}/**/*"
    else
		echo
		echo "build ${pkg}:"
		echo '  variables:'
		echo "    base: $path"
		echo '  extends: .doc'
		echo '  rules:'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /skip-doc/ || $pipeline =~ /skip-doc/"'
		echo '      when: never'
		echo '    - if: "$CI_COMMIT_MESSAGE =~ /force-doc/ || $pipeline =~ /force-doc/"'
		echo '    - changes:'
		echo "      - ${path}/**/*"
    fi
done
